version: "3"
services:
  web:
    # replace balaganur/repo:tag with your name and image details
    image: balaganurrakesh/repo1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
